import React,{useState,useEffect,useRef} from 'react';
import gsap from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import {ArrowUpRight,ArrowRight,Menu,X,Plus,Minus,Play,Pause,Phone} from 'lucide-react';
import {BUSINESS_INFO as B} from '../data/businessData';
import {SERVICES,SERVICE_CATEGORIES} from '../data/servicesData';
gsap.registerPlugin(ScrollTrigger);
const Logo=()=> <span className="brand"><span className="logo-frame"><img src="/szine-monogram.jpg" alt="SZ monogram"/></span><span>SZINE<small>D E T A I L I N G</small></span></span>;
export function LabNav({onNavigate,onOpenWizard,currentPage}){
 const [open,setOpen]=useState(false);
 const jump=id=>{setOpen(false);if(currentPage!=='home')onNavigate('home');setTimeout(()=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'}),80);};
 return <header className="lab-nav"><a className="wordmark" href="#" aria-label="Szine Detailing home" onClick={e=>{e.preventDefault();setOpen(false);onNavigate('home');}}><Logo/></a><nav className={open?'is-open':''} aria-label="Main navigation"><button onClick={()=>jump('services')}>Our services</button><button onClick={()=>jump('craft')}>Our approach</button><button onClick={()=>jump('location')}>Contact</button></nav><div className="nav-actions"><a className="nav-phone" href={'tel:'+B.phone.replace(/\D/g,'')}>Let’s talk <Phone size={14}/></a><button className="lab-button nav-quote" onClick={()=>{setOpen(false);onOpenWizard();}}>Request a quote <ArrowUpRight size={16}/></button><button className="menu-toggle" onClick={()=>setOpen(!open)} aria-label={open?'Close navigation':'Open navigation'} aria-expanded={open}>{open?<X/>:<Menu/>}</button></div></header>;
}
const offers=[{category:'Ceramic Coatings',name:'Ceramic protection',image:'ceramic-coating.jpg',copy:'Keep that freshly detailed feeling for longer, with a glossy protective treatment that makes everyday care easier.',label:'For a finish worth preserving'}, {category:'Paint Correction',name:'Paint correction',image:'paint-correction.jpg',copy:'Bring clarity and depth back to your paint with carefully considered polishing for swirls, haze and surface marks.',label:'For a little more brilliance'},{category:'Interior Restoration',name:'Interior & full detailing',image:'interior-detail.jpg',copy:'A thoughtful refresh for the spaces you see, touch and enjoy. A cleaner cabin and a beautifully finished exterior.',label:'For a fresh start, inside & out'}];
export default function FinishLab({onOpenWizard,onViewAllServices}){
 const root=useRef(null),video=useRef(null);const [playing,setPlaying]=useState(false),[faq,setFaq]=useState(null);
 useEffect(()=>{const mm=gsap.matchMedia();mm.add('(prefers-reduced-motion: no-preference)',()=>{const ctx=gsap.context(()=>{gsap.from('.luxury-hero h1,.hero-intro',{y:24,opacity:0,duration:1,stagger:.12,ease:'power2.out'});gsap.utils.toArray('[data-reveal]').forEach(el=>gsap.from(el,{y:28,opacity:0,duration:.7,scrollTrigger:{trigger:el,start:'top 92%',once:true}}));gsap.to('.luxury-hero-photo img',{yPercent:6,ease:'none',scrollTrigger:{trigger:'.luxury-hero-photo',start:'top bottom',end:'bottom top',scrub:1}});},root);return()=>ctx.revert();});return()=>mm.revert();},[]);
 const film=async()=>{if(playing){video.current.pause();setPlaying(false);}else try{await video.current.play();setPlaying(true);}catch{setPlaying(false);}};
 const questions=[['What does my car need?','You don’t need to know the name of the treatment. Tell us a little about your car and what you’d like to improve. We’ll help you choose the right care for its condition and your priorities.'],['Can you come to my home or office?','We offer mobile detailing across Phoenix Metro and the East Valley. Some treatments are better suited to studio finishing. We’ll discuss access, space and the most convenient option for you.'],['How do I get a price?','Send a quote request with your vehicle details and the service you’re interested in. The team will review it and follow up with a tailored estimate. Your request does not confirm an appointment.'],['Does a ceramic coating remove scratches?','Ceramic coating adds protection; it doesn’t remove scratches. Paint correction can refine eligible surface defects before a coating is applied. We’ll assess the paint before recommending an approach.']];
 return <div ref={root} className="luxury-site"><section className="luxury-hero"><div className="hero-top"><div><span className="eyebrow">EXCEPTIONAL CAR CARE. PERSONAL ATTENTION.</span><h1>A beautiful car.<br/><em>A better feeling.</em></h1></div><div className="hero-intro"><p>Beautifully detailed. Thoughtfully protected.<br/>Car care that makes every drive feel special.</p><button className="lab-button" onClick={()=>onOpenWizard()}>Let’s care for your car <ArrowUpRight size={18}/></button><span className="hero-availability">Mobile & studio care · Phoenix, Arizona</span></div></div><div className="luxury-hero-photo"><img src="/images/luxury-hero.webp" alt="Champagne sports coupe in a sunlit architectural setting — campaign imagery" fetchPriority="high"/><span className="photo-caption">A LITTLE MORE CARE. A LOT MORE PRIDE.</span><a href="#services" className="photo-discover">Discover our services <ArrowRight size={17}/></a></div><div className="care-strip"><span>Care tailored to your vehicle</span><i/><span>Mobile convenience</span><i/><span>A considered finish, inside & out</span></div></section>
 <section className="section-shell services-section" id="services"><div className="section-heading" data-reveal><div><span className="eyebrow">OUR SERVICES</span><h2>Every car deserves<br/><em>a little extraordinary.</em></h2></div><div><p>Whether it’s your daily drive or your pride and joy, we’ll help you find the right treatment.</p><button className="text-link" onClick={onViewAllServices}>View all services <ArrowUpRight size={17}/></button></div></div><div className="treatment-grid">{offers.map((s,i)=><article className="treatment" key={s.name} data-reveal><button className="treatment-photo" aria-label={'Request '+s.name+' quote'} onClick={()=>onOpenWizard(s.category)}><img src={'/images/'+s.image} alt={s.name+' care'} loading="lazy"/><span className="service-number">0{i+1}</span><span className="circle-arrow"><ArrowUpRight size={19}/></span></button><span className="eyebrow service-label">{s.label}</span><h3>{s.name}</h3><p>{s.copy}</p><button className="text-link" onClick={()=>onOpenWizard(s.category)}>Explore your options <ArrowUpRight size={15}/></button></article>)}</div></section>
 <section className="concierge section-shell" id="craft"><div className="concierge-media"><video ref={video} muted loop playsInline preload="none" poster="/images/hero-poster.jpg" onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)}><source src="/images/hero-video.mp4" type="video/mp4"/></video><button className="film-play" onClick={film}>{playing?<Pause size={17}/>:<Play size={17}/>} {playing?'Pause film':'Watch the finish'}</button></div><div className="concierge-copy" data-reveal><span className="eyebrow">THE SZINE APPROACH</span><h2>Considered care.<br/><em>Effortless experience.</em></h2><p>You care about your car. We care about making the experience just as good as the result. From the first conversation to the finishing touches, we keep things personal, clear and convenient.</p><div className="approach-list"><div><span>01</span><p><strong>We listen first.</strong> Your car, its condition and what matters to you.</p></div><div><span>02</span><p><strong>We tailor the care.</strong> The right treatment, explained in plain language.</p></div><div><span>03</span><p><strong>You enjoy the finish.</strong> A considered result and practical advice to care for it.</p></div></div><button className="text-link" onClick={()=>onOpenWizard()}>Tell us about your car <ArrowUpRight size={17}/></button></div></section>
 <section className="location section-shell" id="location"><div data-reveal><span className="eyebrow">CAR CARE, CLOSER TO HOME</span><h2>A little luxury.<br/><em>Right in your driveway.</em></h2><p>Mobile detailing and studio finishing across Phoenix Metro and the East Valley. Let’s find the right care—and the most convenient way to make it happen.</p><div className="location-actions"><button className="lab-button" onClick={()=>onOpenWizard()}>Request your personal quote <ArrowUpRight size={17}/></button><a className="text-link" href={'tel:'+B.phone.replace(/\D/g,'')}>Or call {B.phone} <Phone size={15}/></a></div></div><aside><span className="eyebrow">WHERE WE CARE FOR YOUR CAR</span><p className="service-areas">{B.address.serviceAreas.join(' · ')}</p><div className="hours"><span>Monday – Friday</span><span>7:30 am – 6:30 pm</span><span>Saturday</span><span>8:00 am – 5:00 pm</span><span>Sunday</span><span>By appointment</span></div><a className="text-link" href={B.googleMapsLink} target="_blank" rel="noreferrer">Explore our service area <ArrowUpRight size={16}/></a></aside></section>
 <section className="faq section-shell"><div><span className="eyebrow">A FEW HELPFUL ANSWERS</span><h2>Let’s make<br/><em>it simple.</em></h2></div><div>{questions.map(([q,a],i)=><article key={q}><button aria-expanded={faq===i} aria-controls={'faq-'+i} onClick={()=>setFaq(faq===i?null:i)}>{q}{faq===i?<Minus size={18}/>:<Plus size={18}/>}</button>{faq===i&&<p id={'faq-'+i}>{a}</p>}</article>)}</div></section></div>;
}
export function LabFooter({onNavigate}){return <footer className="lab-footer"><div className="footer-top"><Logo/><p>A beautifully cared-for car.<br/>A feeling you take with you.</p><a href={B.instagram.url} target="_blank" rel="noreferrer">Follow along on Instagram <ArrowUpRight size={17}/></a><a href={'mailto:'+B.email}>Let’s talk <ArrowUpRight size={17}/></a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Szine Detailing</span><span>Phoenix, Arizona</span><button onClick={()=>onNavigate('admin')}>Team access</button></div></footer>}
export function LabServices({onOpenWizard,onBackToHome}){
 const [category,setCategory]=useState('All Services'),[search,setSearch]=useState('');
 const filtered=SERVICES.filter(s=>(category==='All Services'||s.category===category)&&`${s.title} ${s.description}`.toLowerCase().includes(search.toLowerCase()));
 return <section className="lab-catalog section-shell"><button className="text-link" onClick={onBackToHome}>← Back to home</button><span className="eyebrow">CARE TAILORED TO YOUR CAR</span><h1>The right care.<br/><em>For your car.</em></h1><div className="catalog-tools"><label>Search treatments<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Coating, correction, interior…" type="search"/></label><div className="layer-tabs">{SERVICE_CATEGORIES.map(c=><button key={c} className={category===c?'active':''} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div></div><div className="catalog-list">{filtered.map((s,i)=><article key={s.id}><span className="eyebrow">{String(i+1).padStart(2,'0')} / {s.category}</span><div><h2>{s.title}</h2><p>{s.description}</p><details><summary>What’s included</summary><ul>{s.features.map(f=><li key={f}>{f}</li>)}</ul></details></div><button className="lab-button" onClick={()=>onOpenWizard(s.category,s.title)}>Request a quote <ArrowUpRight size={18}/></button></article>)}{!filtered.length&&<p>No treatments match your search. Try another term.</p>}</div></section>;
}
